### ISSUE TITLE
Add config toml for settings

### ISSUE THREAD

**Issue by markhakansson** [markhakansson/rauk#4]
# Summary
Instead of only working with flags and options, there should be a `rauk.toml` as an option.
# Examples
```bash
$ rauk <PATH> --wcet`
```
into
```toml
[project]
path = <PATH>
[flags]
wcet = true
```
# Context
n/a
